### ISSUE TITLE
Not working with latest visual studio Enterprise 2017 

### ISSUE THREAD

**Issue by M2Key** [madskristensen/Angular2Pack#2]
### Installed product versions
- Visual Studio: [Enterprise  2017 latest version 15.1 (26403.7)]
- This extension: [1.0] (latest version from visual studio marketplace)

### Description
The snippet doest not appear

### Steps to recreate
1. Install the Angular 2 pack from visual studio marketplace (from inside or outside of visual studio 2017)
2. go etheir on .ts file or .html file
3. type ng2 to see the list of available snippet
4. Nothing appear, the list is empty

**Comment by kspearrin** [comment]
How did you fix this? I can't seem to get it working in 2017 Enterprise either.
